---
title: "Spokane Fires Situation Report"
subtitle: "Date of Preparation: August 2026"
author:
  - name: "Nikita Jayaprakash"
  - name: "Selina Carter"
  - name: "Samsara Foubert"
thanks: "This report was prepared as part of the partnership between Carnegie Mellon University and Meta's AI for Good."

execute: 
  warning: false
  message: false
  output: false
  echo: false

fig-pos: H

format:
  pdf:
    colorlinks: true
    pdf-engine: xelatex
    tbl-cap-location: bottom
    geometry:
      - margin=0.75in
    include-in-header:
      text: |
        \usepackage{etoolbox}
        \usepackage{fancyhdr}

        \makeatletter
        \patchcmd{\@makefntext}
          {\parindent 1em}
          {\parindent 1em\leftskip -0.5in\rightskip -0.5in}
          {}{}
        \makeatother

        \pagestyle{fancy}
        \fancyhf{}
        \fancyfoot[R]{\thepage}
        \renewcommand{\headrulewidth}{0pt}
        \renewcommand{\footrulewidth}{0pt}
---
# Disaster Manager Brief - Spokane Fires in Washington

## Overview

```{r, warning = F, echo = F}
library(tidyverse)
library(sf)
library(lubridate)
library(gganimate)
library(ggforce)
library(ggspatial)
library(maptiles)
library(quadkeyr)
library(prettymapr)
library(patchwork)
setwd("C:/Users/selin/Dropbox/CMU/Meta_AI_good/fire")
```

Summary here...

```{r, echo = F, warning=F, message = F}
source("1_data_cleaning_Selina.R")

```

## Population Plots

```{r fig-first-day, output = T, fig.cap = "Description here", fig.height = 9}
population_plot("2026-08-03", "0000") /
population_plot("2026-08-03", "0800") /
  population_plot("2026-08-03", "1600")+
  plot_layout(guides = "collect") &
  theme(
    legend.position = "right",
    legend.key.height = unit(2, "cm"),
    legend.direction = "vertical"
  )
```


```{r fig-pop-zoomed, output = T, fig.cap = "description here.", fig.height = 9}
population_plot(
  "2026-08-03", "0000",
  lon_limits = c(-118.5, -115.5),
  lat_limits = c(47, 49)
) / population_plot(
  "2026-08-03", "0800",
  lon_limits = c(-118.5, -115.5),
  lat_limits = c(47, 49)
) / population_plot(
  "2026-08-03", "1600",
  lon_limits = c(-118.5, -115.5),
  lat_limits = c(47, 49)
)+
  plot_layout(guides = "collect") &
  theme(
    legend.position = "right",
    legend.key.height = unit(2, "cm"),
    legend.direction = "vertical"
  )
```
## Movement Plots

```{r}
movement_plot <- function(
  plot_ds,
  plot_hour,
  plot_title,
  lon_limits = NULL,   # c(min_lon, max_lon)
  lat_limits = NULL,    # c(min_lat, max_lat)
  n_limit = NULL
) {
  time_moved <- moved |>
    filter(
      ds == plot_ds,
      hour == plot_hour
    ) |>
    filter(
      (between(start_latitude, lat_limits[1], lat_limits[2]) &between(start_longitude, lon_limits[1], lon_limits[2])) | 
        (between(end_latitude, lat_limits[1], lat_limits[2]) & between(end_longitude, lon_limits[1], lon_limits[2]))
    ) |>
    filter(between(`# Users`, n_limit[1], n_limit[2]))
  
  # plot limits
  plot_lat <- c(
    min(c(time_moved$start_latitude, time_moved$end_latitude)-0.5),
    max(c(time_moved$start_latitude, time_moved$end_latitude))+0.5
  )
  plot_long <- c(
    min(c(time_moved$start_longitude, time_moved$end_longitude))-0.5,
    max(c(time_moved$start_longitude, time_moved$end_longitude))+0.5
  )
  
  n_limit <- c(n_limit[1], max(time_moved$`# Users`))
  
  ggplot() +
    layer_spatial(osm) +
    geom_link(
      data = time_moved,
      aes(
        x = start_longitude,
        y = start_latitude,
        xend = end_longitude,
        yend = end_latitude,
        color = `# Users`
      ),
      alpha = 0.5,
      arrow = arrow(length = unit(0.03, "npc")),
      linewidth = 1
    ) +
    scale_color_gradient(
      low = "blue",
      high = "red",
      limits = n_limit,
      ) +
    coord_sf(
     xlim = plot_long,
     ylim = plot_lat,
      expand = FALSE
    ) +
    theme_minimal() +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank()
    ) +
    ggtitle(plot_title)
}
```

## Small Group Movements

```{r fig-move, output = T, fig.cap = "description here", fig.height = 9}
movement_plot("2026-08-03",
              "0800",
              "Aug 3rd 12am - 8am",
              lon_limits = c(-118.5, -115.5),
              lat_limits = c(47, 49),
              n_limit = c(10, 15)) /
  movement_plot("2026-08-03",
              "1600",
              "Aug 3rd 8am - 4pm",
              lon_limits = c(-118.5, -115.5),
              lat_limits = c(47, 49),
              n_limit = c(10, 15))+
  plot_layout(guides = "collect") &
  theme(
    legend.position = "right",
    legend.key.height = unit(2, "cm"),
    legend.direction = "vertical"
  )

```

## Medium Group Movements

```{r fig-move2, output = T, fig.cap = "description here", fig.height = 9}
movement_plot("2026-08-03",
              "0800",
              "Aug 3rd 12am - 8am",
              lon_limits = c(-118.5, -115.5),
              lat_limits = c(47, 49),
              n_limit = c(15, 25)) /
  movement_plot("2026-08-03",
              "1600",
              "Aug 3rd 8am - 4pm",
              lon_limits = c(-118.5, -115.5),
              lat_limits = c(47, 49),
              n_limit = c(15, 25)) +
  plot_layout(guides = "collect") &
  theme(
    legend.position = "right",
    legend.key.height = unit(2, "cm"),
    legend.direction = "vertical"
  )

```

## Large Group Movements

```{r fig-move3, output = T, fig.cap = "description here", fig.height = 9}
movement_plot("2026-08-03",
              "0800",
              "Aug 3rd 12am - 8am",
              lon_limits = c(-118.5, -115.5),
              lat_limits = c(47, 49),
              n_limit = c(25, 90)) /
  movement_plot("2026-08-03",
              "1600",
              "Aug 3rd 8am - 4pm",
              lon_limits = c(-118.5, -115.5),
              lat_limits = c(47, 49),
              n_limit = c(25, 90)) +
  plot_layout(guides = "collect") &
  theme(
    legend.position = "right",
    legend.key.height = unit(2, "cm"),
    legend.direction = "vertical"
  )

```